version: "3.7"

services:
  menu_db:
    container_name: "menu_services_db"
    hostname: "menu_services_db"
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - menu_network
    ports:
      - "3306:3306"
    env_file:
      - ./.env

    volumes:
      - menu_database:/var/lib/mysql
  menu_api:
    container_name: "menu_services_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: on-failure
    networks:
      - menu_network
    ports:
      - "8090:8090"
    depends_on:
      - menu_db
    env_file:
          - ./.env
    volumes:
      - menu_api:/usr/src/app/

networks:
  menu_network:
volumes:
  menu_database:
  menu_api:
